baseurl: ""
url: ""
menu:
  - url: '/services.html'
    title: Leistungen
  - url: '/customers.html'
    title: Referenzen
  - url: '/certifications.html'
    title: Förderungen
  - url: '/jobs.html'
    title: Jobs
  - url: '/contact.html'
    title: Kontakt
